backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "productos"
    label: "Přívěsy"
    folder: "data/productos"
    create: true
    identifier_field: "nombre"
    slug: "{{nombre | slugify}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "Název přívěsu", name: "nombre", widget: "string" }
      - { label: "Cena", name: "precio", widget: "string" }
      - { label: "Hlavní obrázek", name: "imagen", widget: "image" }
      - { 
          label: "Kategorie", 
          name: "categoria", 
          widget: "select", 
          options: [
            { label: "Přívěsy na koně", value: "prepravniky" },
            { label: "Nákladní přívěsy", value: "nakladni-privesy" },
            { label: "Ostatní", value: "ostatni" }
          ] 
        }
      - { label: "Popis", name: "descripcion", widget: "markdown" }
      - { 
          label: "Galerie obrázků", 
          name: "galeria", 
          widget: "list", 
          fields: [
            { label: "Imagen", name: "imagen", widget: "image" }
          ] 
        }
